apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-dal-talks
  labels:
    app: ms-dal-talks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-dal-talks
  template:
    metadata:
      labels:
        app: ms-dal-talks
    spec:
      containers:
      #---------------------------------------- [CONTAINER:]  -------------------------------#
      - name: ms-dal-talks
        image: gcr.io/kubernetes-101-227215/ms-dal-talks:latest
        ports:
        - name: ms-dal-talks
          containerPort: 9092
          protocol: TCP